version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp # DNS
      - 53:53/udp
      - 853:853/tcp # DNS over TLS
      - 80:80/tcp # Dashboard
      - 443:443/tcp # DNS over HTTPs
      - 443:443/udp
      - 784:784/udp # DNS over QUIC
      - 853:853/udp
      - 3000:3000/tcp # initial installation
    environment:
      - TZ=Europe/Lisbon
    volumes:
      - /home/username/docker/adguard/work:/opt/adguardhome/work
      - /home/username/docker/adguard/conf:/opt/adguardhome/conf
