# Also change the config.yml to:
# parallel_read: true
#   plot_directories:
#   - /mnt/plots

version: '3' 
services: 
      chia-gh-nvidia:
        container_name: chia-gh-nvidia
        restart: unless-stopped
        image: ghcr.io/madmax43v3r/chia-gigahorse:latest-nvidia
        runtime: nvidia
        ports:
            - 8444:8444
            - 8447:8447
        environment: 
            - TZ=Europe/Lisbon 
            - CHIAPOS_MAX_CORES=8
            - CHIAPOS_MAX_CUDA_DEVICES=1
            - NVIDIA_VISIBLE_DEVICES=0
            - CHIAPOS_MAX_OPENCL_DEVICES=0
            - CHIA_ROOT=/root/.chia/mainnet
            - CHIA_UPNP=false
            - CHIA_LOG_LEVEL=INFO
            - PLOTS_DIR=/mnt/plots
            - LOG_TO_FILE=true
        volumes:
            - /home/epical/.chia/.chia_keys:/root/.chia_keys
            - /home/epical/.chia:/root/.chia
            - /mnt/:/mnt/plots
