---
version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname: filebrowser
    environment:
      - TZ=Europe/Lisbon
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/hdd/:/srv
      - /home/username/docker/filebrowser/:/config
    ports:
      - 8080:80
    restart: unless-stopped
