version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /home/username/docker/homer/assets/:/www/assets
    ports:
      - 8888:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=0
