version: "3.5"
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8181:8080" # webapp
      - "8086:8086" # influxDB admin
    environment:
      - COLLECTOR_CRON_SCHEDULE="0 0 * * *"
    volumes:
      - /run/udev:/run/udev:ro
      - /home/username/docker/scrutiny/config:/opt/scrutiny/config
      - /home/username/docker/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
