version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/username/docker/smokeping/config:/config
      - /home/username/docker/smokeping/data:/data
    ports:
      - 4001:80
    restart: unless-stopped
