version: "3"
services:
  watchtower:
    restart: always
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=discord://${DISCORD_TOKEN}@${DISCORD_ID}?title=Watchtower
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=10
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=watchtower
      - WATCHTOWER_SCHEDULE=0 0 5 * * *
      - WATCHTOWER_CLEANUP=true
